### ISSUE TITLE
Able to level-up player byte per click counter

### ISSUE THREAD

**Issue by RomanovYurii** [RomanovYurii/WebClicker#9]
Добавьте, пожалуйста, возможность "прокачивать" уровень персонажа, а соответственно - увеличивать количество зарабатываемых Байтов за клик

**Comment by KKoaran** [comment]
Разделил типы Предметов на "увеличивающие урон в секунду" и "увеличивающие урон от клика". Курсор теперь увеличивает урон от клика вместо постоянного.
